# Generated by Django 5.1.3 on 2024-11-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_complaint_model_feedback_feedback_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_model',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
